hedging:
  LOW_BOUND_RATIO_SHORTING: 0.95
  LOW_SAFEBOUND_RATIO_SHORTING: 0.98
# average: 0.99
  HIGH_SAFEBOUND_RATIO_SHORTING: 1
  HIGH_BOUND_RATIO_SHORTING: 1.03

# take a target leverage and safe parameter and calculate those bounding values dynamically.
  LOW_BOUND_LEVERAGE: 1.2
  LOW_SAFEBOUND_LEVERAGE: 1.8
#  // average: 2
  HIGH_SAFEBOUND_LEVERAGE: 2.25
  HIGH_BOUND_LEVERAGE: 3

  MINIMUM_POSITIVE_LIABILITY_USD: 1
  MINIMUM_TRANSFER_AMOUNT_USD: 100
  MINIMUM_ORDER_SIZE_IN_CONTRACT: 1
  CONTRACT_FACE_VALUE: 100

rebalancing:
  lndHoldingBase: 50000000 # 0.5
  ratioTargetDeposit: 1
  ratioTargetWithdraw: 1
  minOnchain: 10000000 # 0.1

