exchange:
  REQUEST_TIMEOUT: 20000

hedging:
  LOW_BOUND_RATIO_SHORTING: 0.95
  LOW_SAFEBOUND_RATIO_SHORTING: 0.98
# average: 0.99
  HIGH_SAFEBOUND_RATIO_SHORTING: 1
  HIGH_BOUND_RATIO_SHORTING: 1.03

# take a target leverage and safe parameter and calculate those bounding values dynamically.
  LOW_BOUND_LEVERAGE: 1.2
  LOW_SAFEBOUND_LEVERAGE: 1.8
#  // average: 2
  HIGH_SAFEBOUND_LEVERAGE: 2.25
  HIGH_BOUND_LEVERAGE: 3

  MINIMUM_FUNDING_BALANCE_BTC: 1
  MINIMUM_POSITIVE_LIABILITY_USD: 1
  MINIMUM_TRANSFER_AMOUNT_USD: 100
  MINIMUM_ORDER_SIZE_IN_CONTRACT: 1
  CONTRACT_FACE_VALUE: 100

fees:
  BASE_FEE: 0.0005
  IMMEDIATE_CONVERSION_SPREAD: 0.0005
  DELAYED_CONVERSION_SPREAD: 0.0007

withdrawal:
  MIN_ON_CHAIN_WITHDRAWAL_AMOUNT: 0.001
  MIN_ON_CHAIN_WITHDRAWAL_FEE: 0.0002
  MAX_ON_CHAIN_WITHDRAWAL_FEE: 0.0004
