{
 "title": "Galoy Dealer",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Strategy Unrealized PnL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_spotUPnlInUsd)",
     "legendFormat": "spot uPnl in usd"
    },
    {
     "expr": "avg by (container)(galoy_dealer_swapUPnlInUsd)",
     "legendFormat": "swap uPnl in usd"
    },
    {
     "expr": "avg by (container)(galoy_dealer_strategyUPnlInUsd)",
     "legendFormat": "strategy uPnl in usd"
    }
   ]
  },
  {
   "title": "Strategy Realized PnL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_tradingFeesTotalInSats)",
     "legendFormat": "trading fees in sats"
    },
    {
     "expr": "avg by (container)(galoy_dealer_fundingFeesTotalInSats)",
     "legendFormat": "funding fees in sats"
    },
    {
     "expr": "avg by (container)(galoy_dealer_strategyRPnlInSats)",
     "legendFormat": "strategy realized pnl in sats"
    },
    {
     "expr": "avg by (container)(galoy_dealer_strategyRPnlInSats / 100000000 * galoy_dealer_btcSpotPriceInUsd)",
     "legendFormat": "strategy realized pnl in usd"
    }
   ]
  },
  {
   "title": "Funding Fees",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_fundingFeesExpenseInSats)",
     "legendFormat": "funding fees expense"
    },
    {
     "expr": "avg by (container)(galoy_dealer_fundingFeesIncomeInSats)",
     "legendFormat": "funding fees income"
    },
    {
     "expr": "avg by (container)(galoy_dealer_fundingFeesExpenseCount)",
     "legendFormat": "#funding fees expense"
    },
    {
     "expr": "avg by (container)(galoy_dealer_fundingFeesIncomeCount)",
     "legendFormat": "#funding fees income"
    }
   ]
  },
  {
   "title": "Trading Fees",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_tradingFeesBuyInSats)",
     "legendFormat": "trading fees buy"
    },
    {
     "expr": "avg by (container)(galoy_dealer_tradingFeesSellInSats)",
     "legendFormat": "trading fees sell"
    },
    {
     "expr": "avg by (container)(galoy_dealer_tradingFeesBuyCount)",
     "legendFormat": "#trading fees buy"
    },
    {
     "expr": "avg by (container)(galoy_dealer_tradingFeesSellCount)",
     "legendFormat": "#trading fees sell"
    }
   ]
  },
  {
   "title": "Liability in USD & BTC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "avg by (container)(-galoy_dealer_liabilityInUsd)",
     "legendFormat": "liability in usd"
    },
    {
     "expr": "avg by (container)(galoy_dealer_liabilityInBtc)",
     "legendFormat": "liability in btc"
    }
   ]
  },
  {
   "title": "Position Quantity in Contracts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_positionQuantity)",
     "legendFormat": "position"
    }
   ]
  },
  {
   "title": "Average Open Price in USD",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_averageOpenPrice)",
     "legendFormat": "avg open px"
    }
   ]
  },
  {
   "title": "BTC Free/Used/Total Balance on Exchange",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_btcFreeBalance)",
     "legendFormat": "free"
    },
    {
     "expr": "avg by (container)(galoy_dealer_btcUsedBalance)",
     "legendFormat": "used"
    },
    {
     "expr": "avg by (container)(galoy_dealer_btcTotalBalance)",
     "legendFormat": "total"
    },
    {
     "expr": "avg by (container)(galoy_dealer_btcTotalBalance + galoy_dealer_fundingAccountBtcTotalBalance)",
     "legendFormat": "trading & funding total"
    },
    {
     "expr": "avg by (container)(galoy_dealer_fundingAccountBtcTotalBalance)",
     "legendFormat": "funding total"
    }
   ]
  },
  {
   "title": "Margin Leverage Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_btcTotalBalance / galoy_dealer_btcUsedBalance)",
     "legendFormat": "total / used ratio"
    }
   ]
  },
  {
   "title": "Exposure Liability Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_exposureInUsd / (-galoy_dealer_liabilityInUsd))",
     "legendFormat": "exposure / liability"
    }
   ]
  },
  {
   "title": "Exposure Leverage Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_exposureInUsd / galoy_dealer_collateralInUsd)",
     "legendFormat": "exposure / collateral"
    }
   ]
  },
  {
   "title": "Liquidation Price",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_liquidationPrice)",
     "legendFormat": "liq px"
    },
    {
     "expr": "avg by (container)(galoy_dealer_lastBtcPriceInUsd)",
     "legendFormat": "last px"
    }
   ]
  },
  {
   "title": "Unrealized PnL & Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_unrealizedPnLRatio * 100)",
     "legendFormat": "upl ratio"
    },
    {
     "expr": "avg by (container)(galoy_dealer_unrealizedPnL)",
     "legendFormat": "upl"
    }
   ]
  },
  {
   "title": "Auto De-leveraging Indicator",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_autoDeleveragingIndicator)",
     "legendFormat": "adl"
    }
   ]
  },
  {
   "title": "Position Exposure in Usd",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_exposureInUsd)",
     "legendFormat": "exposure usd"
    }
   ]
  },
  {
   "title": "Position vs Exchange Leverage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_leverage)",
     "legendFormat": "position lever"
    },
    {
     "expr": "avg by (container)(galoy_dealer_exchangeLeverage)",
     "legendFormat": "exchange lever"
    }
   ]
  },
  {
   "title": "Total Account Value in Usd",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_totalAccountValueInUsd)",
     "legendFormat": "total equity"
    }
   ]
  },
  {
   "title": "BTC Spot & Perp Price in USD",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_btcSpotPriceInUsd)",
     "legendFormat": "Spot"
    },
    {
     "expr": "avg by (container)(galoy_dealer_btcMarkPriceInUsd)",
     "legendFormat": "Mark"
    },
    {
     "expr": "avg by (container)(galoy_dealer_btcDerivativePriceInUsd)",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "BTCUSD Perp basis in USD",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_btcDerivativePriceInUsd - galoy_dealer_btcSpotPriceInUsd)",
     "legendFormat": "basis"
    }
   ]
  },
  {
   "title": "Maintenance Margin Requirement",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_maintenanceMarginRequirement)",
     "legendFormat": "mmr"
    }
   ]
  },
  {
   "title": "Position Collateral in Usd",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_collateralInUsd)",
     "legendFormat": "collateral usd"
    }
   ]
  },
  {
   "title": "Notional Lever",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_notionalLever)",
     "legendFormat": "notiona lever"
    }
   ]
  },
  {
   "title": "Perp Next Funding Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_nextFundingRate)",
     "legendFormat": "next funding rate"
    }
   ]
  },
  {
   "title": "Margin Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_marginRatio)",
     "legendFormat": "margin ratio"
    }
   ]
  },
  {
   "title": "Exchange Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_exchangeStatus)",
     "legendFormat": "isExchangeAlive"
    }
   ]
  },
  {
   "title": "On Exchange Internal Transfers",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_tradingToFundingSuccessCount)",
     "legendFormat": "done withdraw cnt"
    },
    {
     "expr": "avg by (container)(galoy_dealer_tradingToFundingFailCount)",
     "legendFormat": "failed withdraw cnt"
    },
    {
     "expr": "avg by (container)(galoy_dealer_fundingToTradingSuccessCount)",
     "legendFormat": "done deposit cnt"
    },
    {
     "expr": "avg by (container)(galoy_dealer_fundingToTradingFailCount)",
     "legendFormat": "failed  deposit cnt"
    },
    {
     "expr": "avg by (container)(galoy_dealer_totalInternalTransfersCount)",
     "legendFormat": "total transfer cnt"
    }
   ]
  },
  {
   "title": "InFlight Transfers",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_completedDepositCount)",
     "legendFormat": "done deposit cnt"
    },
    {
     "expr": "avg by (container)(galoy_dealer_pendingDepositCount)",
     "legendFormat": "pend deposit cnt"
    },
    {
     "expr": "avg by (container)(galoy_dealer_completedWithdrawalCount)",
     "legendFormat": "done withdraw cnt"
    },
    {
     "expr": "avg by (container)(galoy_dealer_pendingWithdrawalCount)",
     "legendFormat": "pending withdraw cnt"
    },
    {
     "expr": "avg by (container)(galoy_dealer_totalInFlightTransfersCount)",
     "legendFormat": "total transfer cnt"
    }
   ]
  },
  {
   "title": "Assets - Liability in USD",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "avg by(container) (avg_over_time(USD_price[1h])) * (avg by(container) (avg_over_time(galoy_dealer_btc_balance[1h])) / 100000000 + (avg by(container) (avg_over_time(galoy_dealer_btcTotalBalance[1h])) + avg by(container) (avg_over_time(galoy_dealer_fundingAccountBtcTotalBalance[1h])))) + avg by(container) (avg_over_time(galoy_dealer_swapUPnlInUsd[1h])) + (avg by(container) (avg_over_time(galoy_dealer_usd_balance[1h])) / 100)",
     "legendFormat": "assets vs. liability"
    }
   ]
  },
  {
   "title": "Funding Yield",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (container)(galoy_dealer_fundingYield1d)",
     "legendFormat": "1d"
    },
    {
     "expr": "avg by (container)(galoy_dealer_fundingYield1W)",
     "legendFormat": "1W"
    },
    {
     "expr": "avg by (container)(galoy_dealer_fundingYield2W)",
     "legendFormat": "2W"
    },
    {
     "expr": "avg by (container)(galoy_dealer_fundingYield3W)",
     "legendFormat": "3W"
    },
    {
     "expr": "avg by (container)(galoy_dealer_fundingYield1M)",
     "legendFormat": "1M"
    },
    {
     "expr": "avg by (container)(galoy_dealer_fundingYield2M)",
     "legendFormat": "2M"
    },
    {
     "expr": "avg by (container)(galoy_dealer_fundingYield3M)",
     "legendFormat": "3M"
    },
    {
     "expr": "avg by (container)(galoy_dealer_fundingYield6M)",
     "legendFormat": "6M"
    },
    {
     "expr": "avg by (container)(galoy_dealer_fundingYield1Y)",
     "legendFormat": "1Y"
    },
    {
     "expr": "avg by (container)(galoy_dealer_fundingYield2Y)",
     "legendFormat": "2Y"
    },
    {
     "expr": "avg by (container)(galoy_dealer_fundingYield3Y)",
     "legendFormat": "3Y"
    },
    {
     "expr": "avg by (container)(galoy_dealer_fundingYield5Y)",
     "legendFormat": "5Y"
    }
   ]
  }
 ]
}