apiVersion: vendir.k14s.io/v1alpha1
kind: Config

directories:
- path: vendor
  contents:
  - path: .
    git:
      url: https://github.com/GaloyMoney/concourse-shared.git
      ref: fcc49054423878d680b6a4ac7100ef68f2ab2b84
    includePaths:
    - tasks/**/*
    - config/**/*
    - pipeline-fragments.lib.yml
