// this file is autogenerated by codegen
/* eslint-disable */
import { gql } from "@apollo/client"
import * as Apollo from "@apollo/client"
export type Maybe<T> = T | null
export type InputMaybe<T> = Maybe<T>
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & {
  [SubKey in K]?: Maybe<T[SubKey]>
}
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & {
  [SubKey in K]: Maybe<T[SubKey]>
}
const defaultOptions = {} as const
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string
  String: string
  Boolean: boolean
  Int: number
  Float: number
  /** An Opaque Bearer token */
  AuthToken: string
  /** (Positive) Cent amount (1/100 of a dollar) */
  CentAmount: number
  /** An alias name that a user can set for a wallet (with which they have transactions) */
  ContactAlias: string
  /** Display currency of an account */
  DisplayCurrency: string
  /** Hex-encoded string of 32 bytes */
  Hex32Bytes: string
  Language: string
  LnPaymentPreImage: string
  /** BOLT11 lightning invoice payment request with the amount included */
  LnPaymentRequest: string
  LnPaymentSecret: string
  /** Text field in a lightning payment transaction */
  Memo: string
  /** An address for an on-chain bitcoin destination */
  OnChainAddress: string
  OnChainTxHash: string
  /** An authentication code valid for a single use */
  OneTimeAuthCode: string
  PaymentHash: string
  /** Phone number which includes country code */
  Phone: string
  /** Non-fractional signed whole numeric value between -(2^53) + 1 and 2^53 - 1 */
  SafeInt: number
  /** (Positive) Satoshi amount */
  SatAmount: number
  /** (Positive) amount of seconds */
  Seconds: number
  /** An amount (of a currency) that can be negative (e.g. in a transaction) */
  SignedAmount: number
  /** A string amount (of a currency) that can be negative (e.g. in a transaction) */
  SignedDisplayMajorAmount: string
  /** (Positive) Number of blocks in which the transaction is expected to be confirmed */
  TargetConfirmations: number
  /** Timestamp field, serialized as Unix time (the number of seconds since the Unix epoch) */
  Timestamp: number
  /** Unique identifier of a user */
  Username: string
  /** Unique identifier of a wallet */
  WalletId: string
}

export type Account = {
  readonly csvTransactions: Scalars["String"]
  readonly defaultWalletId: Scalars["WalletId"]
  readonly displayCurrency: Scalars["DisplayCurrency"]
  readonly id: Scalars["ID"]
  readonly limits: AccountLimits
  readonly realtimePrice: RealtimePrice
  readonly transactions?: Maybe<TransactionConnection>
  readonly wallets: ReadonlyArray<Wallet>
}

export type AccountCsvTransactionsArgs = {
  walletIds: ReadonlyArray<Scalars["WalletId"]>
}

export type AccountTransactionsArgs = {
  after?: InputMaybe<Scalars["String"]>
  before?: InputMaybe<Scalars["String"]>
  first?: InputMaybe<Scalars["Int"]>
  last?: InputMaybe<Scalars["Int"]>
  walletIds?: InputMaybe<ReadonlyArray<InputMaybe<Scalars["WalletId"]>>>
}

export type AccountLimit = {
  /** The rolling time interval in seconds that the limits would apply for. */
  readonly interval?: Maybe<Scalars["Seconds"]>
  /** The amount of cents remaining below the limit for the current 24 hour period. */
  readonly remainingLimit?: Maybe<Scalars["CentAmount"]>
  /** The current maximum limit for a given 24 hour period. */
  readonly totalLimit: Scalars["CentAmount"]
}

export type AccountLimits = {
  readonly __typename: "AccountLimits"
  /** Limits for converting between currencies among a account's own wallets. */
  readonly convert: ReadonlyArray<AccountLimit>
  /** Limits for sending to other internal accounts. */
  readonly internalSend: ReadonlyArray<AccountLimit>
  /** Limits for withdrawing to external onchain or lightning destinations. */
  readonly withdrawal: ReadonlyArray<AccountLimit>
}

export type AccountUpdateDefaultWalletIdInput = {
  readonly walletId: Scalars["WalletId"]
}

export type AccountUpdateDefaultWalletIdPayload = {
  readonly __typename: "AccountUpdateDefaultWalletIdPayload"
  readonly account?: Maybe<ConsumerAccount>
  readonly errors: ReadonlyArray<Error>
}

export type AccountUpdateDisplayCurrencyInput = {
  readonly currency: Scalars["DisplayCurrency"]
}

export type AccountUpdateDisplayCurrencyPayload = {
  readonly __typename: "AccountUpdateDisplayCurrencyPayload"
  readonly account?: Maybe<ConsumerAccount>
  readonly errors: ReadonlyArray<Error>
}

export type AuthTokenPayload = {
  readonly __typename: "AuthTokenPayload"
  readonly authToken?: Maybe<Scalars["AuthToken"]>
  readonly errors: ReadonlyArray<Error>
}

/** A wallet belonging to an account which contains a BTC balance and a list of transactions. */
export type BtcWallet = Wallet & {
  readonly __typename: "BTCWallet"
  readonly accountId: Scalars["ID"]
  /** A balance stored in BTC. */
  readonly balance: Scalars["SignedAmount"]
  readonly id: Scalars["ID"]
  /** An unconfirmed incoming onchain balance. */
  readonly pendingIncomingBalance: Scalars["SignedAmount"]
  /** A list of BTC transactions associated with this wallet. */
  readonly transactions?: Maybe<TransactionConnection>
  readonly transactionsByAddress?: Maybe<TransactionConnection>
  readonly walletCurrency: WalletCurrency
}

/** A wallet belonging to an account which contains a BTC balance and a list of transactions. */
export type BtcWalletTransactionsArgs = {
  after?: InputMaybe<Scalars["String"]>
  before?: InputMaybe<Scalars["String"]>
  first?: InputMaybe<Scalars["Int"]>
  last?: InputMaybe<Scalars["Int"]>
}

/** A wallet belonging to an account which contains a BTC balance and a list of transactions. */
export type BtcWalletTransactionsByAddressArgs = {
  address: Scalars["OnChainAddress"]
  after?: InputMaybe<Scalars["String"]>
  before?: InputMaybe<Scalars["String"]>
  first?: InputMaybe<Scalars["Int"]>
  last?: InputMaybe<Scalars["Int"]>
}

export type BuildInformation = {
  readonly __typename: "BuildInformation"
  readonly buildTime?: Maybe<Scalars["Timestamp"]>
  readonly commitHash?: Maybe<Scalars["String"]>
  readonly helmRevision?: Maybe<Scalars["Int"]>
}

export type CaptchaCreateChallengePayload = {
  readonly __typename: "CaptchaCreateChallengePayload"
  readonly errors: ReadonlyArray<Error>
  readonly result?: Maybe<CaptchaCreateChallengeResult>
}

export type CaptchaCreateChallengeResult = {
  readonly __typename: "CaptchaCreateChallengeResult"
  readonly challengeCode: Scalars["String"]
  readonly failbackMode: Scalars["Boolean"]
  readonly id: Scalars["String"]
  readonly newCaptcha: Scalars["Boolean"]
}

export type CaptchaRequestAuthCodeInput = {
  readonly challengeCode: Scalars["String"]
  readonly channel?: InputMaybe<PhoneCodeChannelType>
  readonly phone: Scalars["Phone"]
  readonly secCode: Scalars["String"]
  readonly validationCode: Scalars["String"]
}

export type CentAmountPayload = {
  readonly __typename: "CentAmountPayload"
  readonly amount?: Maybe<Scalars["CentAmount"]>
  readonly errors: ReadonlyArray<Error>
}

export type ConsumerAccount = Account & {
  readonly __typename: "ConsumerAccount"
  /** return CSV stream, base64 encoded, of the list of transactions in the wallet */
  readonly csvTransactions: Scalars["String"]
  readonly defaultWalletId: Scalars["WalletId"]
  readonly displayCurrency: Scalars["DisplayCurrency"]
  readonly id: Scalars["ID"]
  readonly limits: AccountLimits
  /** List the quiz questions of the consumer account */
  readonly quiz: ReadonlyArray<Quiz>
  readonly realtimePrice: RealtimePrice
  /** A list of all transactions associated with walletIds optionally passed. */
  readonly transactions?: Maybe<TransactionConnection>
  readonly wallets: ReadonlyArray<Wallet>
}

export type ConsumerAccountCsvTransactionsArgs = {
  walletIds: ReadonlyArray<Scalars["WalletId"]>
}

export type ConsumerAccountTransactionsArgs = {
  after?: InputMaybe<Scalars["String"]>
  before?: InputMaybe<Scalars["String"]>
  first?: InputMaybe<Scalars["Int"]>
  last?: InputMaybe<Scalars["Int"]>
  walletIds?: InputMaybe<ReadonlyArray<InputMaybe<Scalars["WalletId"]>>>
}

export type Coordinates = {
  readonly __typename: "Coordinates"
  readonly latitude: Scalars["Float"]
  readonly longitude: Scalars["Float"]
}

export type Currency = {
  readonly __typename: "Currency"
  readonly flag: Scalars["String"]
  readonly fractionDigits: Scalars["Int"]
  readonly id: Scalars["ID"]
  readonly name: Scalars["String"]
  readonly symbol: Scalars["String"]
}

export type DeviceNotificationTokenCreateInput = {
  readonly deviceToken: Scalars["String"]
}

export type Error = {
  readonly code?: Maybe<Scalars["String"]>
  readonly message: Scalars["String"]
  readonly path?: Maybe<ReadonlyArray<Maybe<Scalars["String"]>>>
}

export const ExchangeCurrencyUnit = {
  Btcsat: "BTCSAT",
  Usdcent: "USDCENT",
} as const

export type ExchangeCurrencyUnit =
  typeof ExchangeCurrencyUnit[keyof typeof ExchangeCurrencyUnit]
/** Provides global settings for the application which might have an impact for the user. */
export type Globals = {
  readonly __typename: "Globals"
  readonly buildInformation: BuildInformation
  /** The domain name for lightning addresses accepted by this Galoy instance */
  readonly lightningAddressDomain: Scalars["String"]
  readonly lightningAddressDomainAliases: ReadonlyArray<Scalars["String"]>
  /** Which network (mainnet, testnet, regtest, signet) this instance is running on. */
  readonly network: Network
  /**
   * A list of public keys for the running lightning nodes.
   * This can be used to know if an invoice belongs to one of our nodes.
   */
  readonly nodesIds: ReadonlyArray<Scalars["String"]>
}

export type GraphQlApplicationError = Error & {
  readonly __typename: "GraphQLApplicationError"
  readonly code?: Maybe<Scalars["String"]>
  readonly message: Scalars["String"]
  readonly path?: Maybe<ReadonlyArray<Maybe<Scalars["String"]>>>
}

export type InitiationVia =
  | InitiationViaIntraLedger
  | InitiationViaLn
  | InitiationViaOnChain

export type InitiationViaIntraLedger = {
  readonly __typename: "InitiationViaIntraLedger"
  readonly counterPartyUsername?: Maybe<Scalars["Username"]>
  readonly counterPartyWalletId?: Maybe<Scalars["WalletId"]>
}

export type InitiationViaLn = {
  readonly __typename: "InitiationViaLn"
  readonly paymentHash: Scalars["PaymentHash"]
}

export type InitiationViaOnChain = {
  readonly __typename: "InitiationViaOnChain"
  readonly address: Scalars["OnChainAddress"]
}

export type IntraLedgerPaymentSendInput = {
  /** Amount in satoshis. */
  readonly amount: Scalars["SatAmount"]
  /** Optional memo to be attached to the payment. */
  readonly memo?: InputMaybe<Scalars["Memo"]>
  readonly recipientWalletId: Scalars["WalletId"]
  /** The wallet ID of the sender. */
  readonly walletId: Scalars["WalletId"]
}

export type IntraLedgerUpdate = {
  readonly __typename: "IntraLedgerUpdate"
  readonly amount: Scalars["SatAmount"]
  readonly displayCurrencyPerSat: Scalars["Float"]
  readonly txNotificationType: TxNotificationType
  /** @deprecated updated over displayCurrencyPerSat */
  readonly usdPerSat: Scalars["Float"]
  readonly walletId: Scalars["WalletId"]
}

export type IntraLedgerUsdPaymentSendInput = {
  /** Amount in cents. */
  readonly amount: Scalars["CentAmount"]
  /** Optional memo to be attached to the payment. */
  readonly memo?: InputMaybe<Scalars["Memo"]>
  readonly recipientWalletId: Scalars["WalletId"]
  /** The wallet ID of the sender. */
  readonly walletId: Scalars["WalletId"]
}

export const InvoicePaymentStatus = {
  Paid: "PAID",
  Pending: "PENDING",
} as const

export type InvoicePaymentStatus =
  typeof InvoicePaymentStatus[keyof typeof InvoicePaymentStatus]
export type LnInvoice = {
  readonly __typename: "LnInvoice"
  readonly paymentHash: Scalars["PaymentHash"]
  readonly paymentRequest: Scalars["LnPaymentRequest"]
  readonly paymentSecret: Scalars["LnPaymentSecret"]
  readonly satoshis?: Maybe<Scalars["SatAmount"]>
}

export type LnInvoiceCreateInput = {
  /** Amount in satoshis. */
  readonly amount: Scalars["SatAmount"]
  /** Optional memo for the lightning invoice. */
  readonly memo?: InputMaybe<Scalars["Memo"]>
  /** Wallet ID for a BTC wallet belonging to the current account. */
  readonly walletId: Scalars["WalletId"]
}

export type LnInvoiceCreateOnBehalfOfRecipientInput = {
  /** Amount in satoshis. */
  readonly amount: Scalars["SatAmount"]
  readonly descriptionHash?: InputMaybe<Scalars["Hex32Bytes"]>
  /** Optional memo for the lightning invoice. */
  readonly memo?: InputMaybe<Scalars["Memo"]>
  /** Wallet ID for a BTC wallet which belongs to any account. */
  readonly recipientWalletId: Scalars["WalletId"]
}

export type LnInvoiceFeeProbeInput = {
  readonly paymentRequest: Scalars["LnPaymentRequest"]
  readonly walletId: Scalars["WalletId"]
}

export type LnInvoicePayload = {
  readonly __typename: "LnInvoicePayload"
  readonly errors: ReadonlyArray<Error>
  readonly invoice?: Maybe<LnInvoice>
}

export type LnInvoicePaymentInput = {
  /** Optional memo to associate with the lightning invoice. */
  readonly memo?: InputMaybe<Scalars["Memo"]>
  /** Payment request representing the invoice which is being paid. */
  readonly paymentRequest: Scalars["LnPaymentRequest"]
  /** Wallet ID with sufficient balance to cover amount of invoice.  Must belong to the account of the current user. */
  readonly walletId: Scalars["WalletId"]
}

export type LnInvoicePaymentStatusInput = {
  readonly paymentRequest: Scalars["LnPaymentRequest"]
}

export type LnInvoicePaymentStatusPayload = {
  readonly __typename: "LnInvoicePaymentStatusPayload"
  readonly errors: ReadonlyArray<Error>
  readonly status?: Maybe<InvoicePaymentStatus>
}

export type LnNoAmountInvoice = {
  readonly __typename: "LnNoAmountInvoice"
  readonly paymentHash: Scalars["PaymentHash"]
  readonly paymentRequest: Scalars["LnPaymentRequest"]
  readonly paymentSecret: Scalars["LnPaymentSecret"]
}

export type LnNoAmountInvoiceCreateInput = {
  /** Optional memo for the lightning invoice. */
  readonly memo?: InputMaybe<Scalars["Memo"]>
  /** ID for either a USD or BTC wallet belonging to the account of the current user. */
  readonly walletId: Scalars["WalletId"]
}

export type LnNoAmountInvoiceCreateOnBehalfOfRecipientInput = {
  /** Optional memo for the lightning invoice. */
  readonly memo?: InputMaybe<Scalars["Memo"]>
  /** ID for either a USD or BTC wallet which belongs to the account of any user. */
  readonly recipientWalletId: Scalars["WalletId"]
}

export type LnNoAmountInvoiceFeeProbeInput = {
  readonly amount: Scalars["SatAmount"]
  readonly paymentRequest: Scalars["LnPaymentRequest"]
  readonly walletId: Scalars["WalletId"]
}

export type LnNoAmountInvoicePayload = {
  readonly __typename: "LnNoAmountInvoicePayload"
  readonly errors: ReadonlyArray<Error>
  readonly invoice?: Maybe<LnNoAmountInvoice>
}

export type LnNoAmountInvoicePaymentInput = {
  /** Amount to pay in satoshis. */
  readonly amount: Scalars["SatAmount"]
  /** Optional memo to associate with the lightning invoice. */
  readonly memo?: InputMaybe<Scalars["Memo"]>
  /** Payment request representing the invoice which is being paid. */
  readonly paymentRequest: Scalars["LnPaymentRequest"]
  /** Wallet ID with sufficient balance to cover amount defined in mutation request.  Must belong to the account of the current user. */
  readonly walletId: Scalars["WalletId"]
}

export type LnNoAmountUsdInvoiceFeeProbeInput = {
  readonly amount: Scalars["CentAmount"]
  readonly paymentRequest: Scalars["LnPaymentRequest"]
  readonly walletId: Scalars["WalletId"]
}

export type LnNoAmountUsdInvoicePaymentInput = {
  /** Amount to pay in USD cents. */
  readonly amount: Scalars["CentAmount"]
  /** Optional memo to associate with the lightning invoice. */
  readonly memo?: InputMaybe<Scalars["Memo"]>
  /** Payment request representing the invoice which is being paid. */
  readonly paymentRequest: Scalars["LnPaymentRequest"]
  /** Wallet ID with sufficient balance to cover amount defined in mutation request.  Must belong to the account of the current user. */
  readonly walletId: Scalars["WalletId"]
}

export type LnUpdate = {
  readonly __typename: "LnUpdate"
  readonly paymentHash: Scalars["PaymentHash"]
  readonly status: InvoicePaymentStatus
  readonly walletId: Scalars["WalletId"]
}

export type LnUsdInvoiceCreateInput = {
  /** Amount in USD cents. */
  readonly amount: Scalars["CentAmount"]
  /** Optional memo for the lightning invoice. */
  readonly memo?: InputMaybe<Scalars["Memo"]>
  /** Wallet ID for a USD wallet belonging to the current user. */
  readonly walletId: Scalars["WalletId"]
}

export type LnUsdInvoiceCreateOnBehalfOfRecipientInput = {
  /** Amount in USD cents. */
  readonly amount: Scalars["CentAmount"]
  readonly descriptionHash?: InputMaybe<Scalars["Hex32Bytes"]>
  /** Optional memo for the lightning invoice. Acts as a note to the recipient. */
  readonly memo?: InputMaybe<Scalars["Memo"]>
  /** Wallet ID for a USD wallet which belongs to the account of any user. */
  readonly recipientWalletId: Scalars["WalletId"]
}

export type LnUsdInvoiceFeeProbeInput = {
  readonly paymentRequest: Scalars["LnPaymentRequest"]
  readonly walletId: Scalars["WalletId"]
}

export type MapInfo = {
  readonly __typename: "MapInfo"
  readonly coordinates: Coordinates
  readonly title: Scalars["String"]
}

export type MapMarker = {
  readonly __typename: "MapMarker"
  readonly mapInfo: MapInfo
  readonly username?: Maybe<Scalars["Username"]>
}

export type MobileVersions = {
  readonly __typename: "MobileVersions"
  readonly currentSupported: Scalars["Int"]
  readonly minSupported: Scalars["Int"]
  readonly platform: Scalars["String"]
}

export type Mutation = {
  readonly __typename: "Mutation"
  readonly accountUpdateDefaultWalletId: AccountUpdateDefaultWalletIdPayload
  readonly accountUpdateDisplayCurrency: AccountUpdateDisplayCurrencyPayload
  readonly captchaCreateChallenge: CaptchaCreateChallengePayload
  readonly captchaRequestAuthCode: SuccessPayload
  readonly deviceNotificationTokenCreate: SuccessPayload
  /**
   * Actions a payment which is internal to the ledger e.g. it does
   * not use onchain/lightning. Returns payment status (success,
   * failed, pending, already_paid).
   */
  readonly intraLedgerPaymentSend: PaymentSendPayload
  /**
   * Actions a payment which is internal to the ledger e.g. it does
   * not use onchain/lightning. Returns payment status (success,
   * failed, pending, already_paid).
   */
  readonly intraLedgerUsdPaymentSend: PaymentSendPayload
  /**
   * Returns a lightning invoice for an associated wallet.
   * When invoice is paid the value will be credited to a BTC wallet.
   * Expires after 24 hours.
   */
  readonly lnInvoiceCreate: LnInvoicePayload
  /**
   * Returns a lightning invoice for an associated wallet.
   * When invoice is paid the value will be credited to a BTC wallet.
   * Expires after 24 hours.
   */
  readonly lnInvoiceCreateOnBehalfOfRecipient: LnInvoicePayload
  readonly lnInvoiceFeeProbe: SatAmountPayload
  /**
   * Pay a lightning invoice using a balance from a wallet which is owned by the account of the current user.
   * Provided wallet can be USD or BTC and must have sufficient balance to cover amount in lightning invoice.
   * Returns payment status (success, failed, pending, already_paid).
   */
  readonly lnInvoicePaymentSend: PaymentSendPayload
  /**
   * Returns a lightning invoice for an associated wallet.
   * Can be used to receive any supported currency value (currently USD or BTC).
   * Expires after 24 hours.
   */
  readonly lnNoAmountInvoiceCreate: LnNoAmountInvoicePayload
  /**
   * Returns a lightning invoice for an associated wallet.
   * Can be used to receive any supported currency value (currently USD or BTC).
   * Expires after 24 hours.
   */
  readonly lnNoAmountInvoiceCreateOnBehalfOfRecipient: LnNoAmountInvoicePayload
  readonly lnNoAmountInvoiceFeeProbe: SatAmountPayload
  /**
   * Pay a lightning invoice using a balance from a wallet which is owned by the account of the current user.
   * Provided wallet must be BTC and must have sufficient balance to cover amount specified in mutation request.
   * Returns payment status (success, failed, pending, already_paid).
   */
  readonly lnNoAmountInvoicePaymentSend: PaymentSendPayload
  readonly lnNoAmountUsdInvoiceFeeProbe: CentAmountPayload
  /**
   * Pay a lightning invoice using a balance from a wallet which is owned by the account of the current user.
   * Provided wallet must be USD and have sufficient balance to cover amount specified in mutation request.
   * Returns payment status (success, failed, pending, already_paid).
   */
  readonly lnNoAmountUsdInvoicePaymentSend: PaymentSendPayload
  /**
   * Returns a lightning invoice denominated in satoshis for an associated wallet.
   * When invoice is paid the equivalent value at invoice creation will be credited to a USD wallet.
   * Expires after 5 minutes (short expiry time because there is a USD/BTC exchange rate
   * associated with the amount).
   */
  readonly lnUsdInvoiceCreate: LnInvoicePayload
  /**
   * Returns a lightning invoice denominated in satoshis for an associated wallet.
   * When invoice is paid the equivalent value at invoice creation will be credited to a USD wallet.
   * Expires after 5 minutes (short expiry time because there is a USD/BTC exchange rate
   *   associated with the amount).
   */
  readonly lnUsdInvoiceCreateOnBehalfOfRecipient: LnInvoicePayload
  readonly lnUsdInvoiceFeeProbe: SatAmountPayload
  readonly onChainAddressCreate: OnChainAddressPayload
  readonly onChainAddressCurrent: OnChainAddressPayload
  readonly onChainPaymentSend: PaymentSendPayload
  readonly onChainPaymentSendAll: PaymentSendPayload
  readonly onChainUsdPaymentSend: PaymentSendPayload
  readonly quizCompleted: QuizCompletedPayload
  /** @deprecated will be moved to AccountContact */
  readonly userContactUpdateAlias: UserContactUpdateAliasPayload
  readonly userLogin: AuthTokenPayload
  readonly userLogout: AuthTokenPayload
  /** @deprecated Use QuizCompletedMutation instead */
  readonly userQuizQuestionUpdateCompleted: UserQuizQuestionUpdateCompletedPayload
  readonly userRequestAuthCode: SuccessPayload
  readonly userUpdateLanguage: UserUpdateLanguagePayload
  /** @deprecated Username will be moved to @Handle in Accounts. Also SetUsername naming should be used instead of UpdateUsername to reflect the idempotency of Handles */
  readonly userUpdateUsername: UserUpdateUsernamePayload
}

export type MutationAccountUpdateDefaultWalletIdArgs = {
  input: AccountUpdateDefaultWalletIdInput
}

export type MutationAccountUpdateDisplayCurrencyArgs = {
  input: AccountUpdateDisplayCurrencyInput
}

export type MutationCaptchaRequestAuthCodeArgs = {
  input: CaptchaRequestAuthCodeInput
}

export type MutationDeviceNotificationTokenCreateArgs = {
  input: DeviceNotificationTokenCreateInput
}

export type MutationIntraLedgerPaymentSendArgs = {
  input: IntraLedgerPaymentSendInput
}

export type MutationIntraLedgerUsdPaymentSendArgs = {
  input: IntraLedgerUsdPaymentSendInput
}

export type MutationLnInvoiceCreateArgs = {
  input: LnInvoiceCreateInput
}

export type MutationLnInvoiceCreateOnBehalfOfRecipientArgs = {
  input: LnInvoiceCreateOnBehalfOfRecipientInput
}

export type MutationLnInvoiceFeeProbeArgs = {
  input: LnInvoiceFeeProbeInput
}

export type MutationLnInvoicePaymentSendArgs = {
  input: LnInvoicePaymentInput
}

export type MutationLnNoAmountInvoiceCreateArgs = {
  input: LnNoAmountInvoiceCreateInput
}

export type MutationLnNoAmountInvoiceCreateOnBehalfOfRecipientArgs = {
  input: LnNoAmountInvoiceCreateOnBehalfOfRecipientInput
}

export type MutationLnNoAmountInvoiceFeeProbeArgs = {
  input: LnNoAmountInvoiceFeeProbeInput
}

export type MutationLnNoAmountInvoicePaymentSendArgs = {
  input: LnNoAmountInvoicePaymentInput
}

export type MutationLnNoAmountUsdInvoiceFeeProbeArgs = {
  input: LnNoAmountUsdInvoiceFeeProbeInput
}

export type MutationLnNoAmountUsdInvoicePaymentSendArgs = {
  input: LnNoAmountUsdInvoicePaymentInput
}

export type MutationLnUsdInvoiceCreateArgs = {
  input: LnUsdInvoiceCreateInput
}

export type MutationLnUsdInvoiceCreateOnBehalfOfRecipientArgs = {
  input: LnUsdInvoiceCreateOnBehalfOfRecipientInput
}

export type MutationLnUsdInvoiceFeeProbeArgs = {
  input: LnUsdInvoiceFeeProbeInput
}

export type MutationOnChainAddressCreateArgs = {
  input: OnChainAddressCreateInput
}

export type MutationOnChainAddressCurrentArgs = {
  input: OnChainAddressCurrentInput
}

export type MutationOnChainPaymentSendArgs = {
  input: OnChainPaymentSendInput
}

export type MutationOnChainPaymentSendAllArgs = {
  input: OnChainPaymentSendAllInput
}

export type MutationOnChainUsdPaymentSendArgs = {
  input: OnChainUsdPaymentSendInput
}

export type MutationQuizCompletedArgs = {
  input: QuizCompletedInput
}

export type MutationUserContactUpdateAliasArgs = {
  input: UserContactUpdateAliasInput
}

export type MutationUserLoginArgs = {
  input: UserLoginInput
}

export type MutationUserLogoutArgs = {
  input: UserLogoutInput
}

export type MutationUserQuizQuestionUpdateCompletedArgs = {
  input: UserQuizQuestionUpdateCompletedInput
}

export type MutationUserRequestAuthCodeArgs = {
  input: UserRequestAuthCodeInput
}

export type MutationUserUpdateLanguageArgs = {
  input: UserUpdateLanguageInput
}

export type MutationUserUpdateUsernameArgs = {
  input: UserUpdateUsernameInput
}

export type MyUpdatesPayload = {
  readonly __typename: "MyUpdatesPayload"
  readonly errors: ReadonlyArray<Error>
  readonly me?: Maybe<User>
  readonly update?: Maybe<UserUpdate>
}

export const Network = {
  Mainnet: "mainnet",
  Regtest: "regtest",
  Signet: "signet",
  Testnet: "testnet",
} as const

export type Network = typeof Network[keyof typeof Network]
export type OnChainAddressCreateInput = {
  readonly walletId: Scalars["WalletId"]
}

export type OnChainAddressCurrentInput = {
  readonly walletId: Scalars["WalletId"]
}

export type OnChainAddressPayload = {
  readonly __typename: "OnChainAddressPayload"
  readonly address?: Maybe<Scalars["OnChainAddress"]>
  readonly errors: ReadonlyArray<Error>
}

export type OnChainPaymentSendAllInput = {
  readonly address: Scalars["OnChainAddress"]
  readonly memo?: InputMaybe<Scalars["Memo"]>
  readonly targetConfirmations?: InputMaybe<Scalars["TargetConfirmations"]>
  readonly walletId: Scalars["WalletId"]
}

export type OnChainPaymentSendInput = {
  readonly address: Scalars["OnChainAddress"]
  readonly amount: Scalars["SatAmount"]
  readonly memo?: InputMaybe<Scalars["Memo"]>
  readonly targetConfirmations?: InputMaybe<Scalars["TargetConfirmations"]>
  readonly walletId: Scalars["WalletId"]
}

export type OnChainTxFee = {
  readonly __typename: "OnChainTxFee"
  readonly amount: Scalars["SatAmount"]
  readonly targetConfirmations: Scalars["TargetConfirmations"]
}

export type OnChainUpdate = {
  readonly __typename: "OnChainUpdate"
  readonly amount: Scalars["SatAmount"]
  readonly displayCurrencyPerSat: Scalars["Float"]
  readonly txHash: Scalars["OnChainTxHash"]
  readonly txNotificationType: TxNotificationType
  /** @deprecated updated over displayCurrencyPerSat */
  readonly usdPerSat: Scalars["Float"]
  readonly walletId: Scalars["WalletId"]
}

export type OnChainUsdPaymentSendInput = {
  readonly address: Scalars["OnChainAddress"]
  readonly amount: Scalars["CentAmount"]
  readonly memo?: InputMaybe<Scalars["Memo"]>
  readonly targetConfirmations?: InputMaybe<Scalars["TargetConfirmations"]>
  readonly walletId: Scalars["WalletId"]
}

export type OnChainUsdTxFee = {
  readonly __typename: "OnChainUsdTxFee"
  readonly amount: Scalars["CentAmount"]
  readonly targetConfirmations: Scalars["TargetConfirmations"]
}

export type OneDayAccountLimit = AccountLimit & {
  readonly __typename: "OneDayAccountLimit"
  /** The rolling time interval value in seconds for the current 24 hour period. */
  readonly interval?: Maybe<Scalars["Seconds"]>
  /** The amount of cents remaining below the limit for the current 24 hour period. */
  readonly remainingLimit?: Maybe<Scalars["CentAmount"]>
  /** The current maximum limit for a given 24 hour period. */
  readonly totalLimit: Scalars["CentAmount"]
}

/** Information about pagination in a connection. */
export type PageInfo = {
  readonly __typename: "PageInfo"
  /** When paginating forwards, the cursor to continue. */
  readonly endCursor?: Maybe<Scalars["String"]>
  /** When paginating forwards, are there more items? */
  readonly hasNextPage: Scalars["Boolean"]
  /** When paginating backwards, are there more items? */
  readonly hasPreviousPage: Scalars["Boolean"]
  /** When paginating backwards, the cursor to continue. */
  readonly startCursor?: Maybe<Scalars["String"]>
}

export type PaymentSendPayload = {
  readonly __typename: "PaymentSendPayload"
  readonly errors: ReadonlyArray<Error>
  readonly status?: Maybe<PaymentSendResult>
}

export const PaymentSendResult = {
  AlreadyPaid: "ALREADY_PAID",
  Failure: "FAILURE",
  Pending: "PENDING",
  Success: "SUCCESS",
} as const

export type PaymentSendResult = typeof PaymentSendResult[keyof typeof PaymentSendResult]
export const PhoneCodeChannelType = {
  Sms: "SMS",
  Whatsapp: "WHATSAPP",
} as const

export type PhoneCodeChannelType =
  typeof PhoneCodeChannelType[keyof typeof PhoneCodeChannelType]
/** Price amount expressed in base/offset. To calculate, use: `base / 10^offset` */
export type Price = {
  readonly __typename: "Price"
  readonly base: Scalars["SafeInt"]
  readonly currencyUnit: Scalars["String"]
  readonly formattedAmount: Scalars["String"]
  readonly offset: Scalars["Int"]
}

/** The range for the X axis in the BTC price graph */
export const PriceGraphRange = {
  FiveYears: "FIVE_YEARS",
  OneDay: "ONE_DAY",
  OneMonth: "ONE_MONTH",
  OneWeek: "ONE_WEEK",
  OneYear: "ONE_YEAR",
} as const

export type PriceGraphRange = typeof PriceGraphRange[keyof typeof PriceGraphRange]
export type PriceInput = {
  readonly amount: Scalars["SatAmount"]
  readonly amountCurrencyUnit: ExchangeCurrencyUnit
  readonly priceCurrencyUnit: ExchangeCurrencyUnit
}

export type PriceInterface = {
  readonly base: Scalars["SafeInt"]
  /** @deprecated Deprecated due to type renaming */
  readonly currencyUnit: Scalars["String"]
  readonly offset: Scalars["Int"]
}

/** Price of 1 sat in base/offset. To calculate, use: `base / 10^offset` */
export type PriceOfOneSatInMinorUnit = PriceInterface & {
  readonly __typename: "PriceOfOneSatInMinorUnit"
  readonly base: Scalars["SafeInt"]
  /** @deprecated Deprecated due to type renaming */
  readonly currencyUnit: Scalars["String"]
  readonly offset: Scalars["Int"]
}

/** Price of 1 sat or 1 usd cent in base/offset. To calculate, use: `base / 10^offset` */
export type PriceOfOneSettlementMinorUnitInDisplayMinorUnit = PriceInterface & {
  readonly __typename: "PriceOfOneSettlementMinorUnitInDisplayMinorUnit"
  readonly base: Scalars["SafeInt"]
  /** @deprecated Deprecated due to type renaming */
  readonly currencyUnit: Scalars["String"]
  /** @deprecated Deprecated please use `base / 10^offset` */
  readonly formattedAmount: Scalars["String"]
  readonly offset: Scalars["Int"]
}

/** Price of 1 usd cent in base/offset. To calculate, use: `base / 10^offset` */
export type PriceOfOneUsdCentInMinorUnit = PriceInterface & {
  readonly __typename: "PriceOfOneUsdCentInMinorUnit"
  readonly base: Scalars["SafeInt"]
  /** @deprecated Deprecated due to type renaming */
  readonly currencyUnit: Scalars["String"]
  readonly offset: Scalars["Int"]
}

export type PricePayload = {
  readonly __typename: "PricePayload"
  readonly errors: ReadonlyArray<Error>
  readonly price?: Maybe<Price>
}

export type PricePoint = {
  readonly __typename: "PricePoint"
  readonly price: Price
  /** Unix timestamp (number of seconds elapsed since January 1, 1970 00:00:00 UTC) */
  readonly timestamp: Scalars["Timestamp"]
}

/** A public view of a generic wallet which stores value in one of our supported currencies. */
export type PublicWallet = {
  readonly __typename: "PublicWallet"
  readonly id: Scalars["ID"]
  readonly walletCurrency: WalletCurrency
}

export type Query = {
  readonly __typename: "Query"
  readonly accountDefaultWallet: PublicWallet
  /** @deprecated Deprecated in favor of realtimePrice */
  readonly btcPrice?: Maybe<Price>
  readonly btcPriceList?: Maybe<ReadonlyArray<Maybe<PricePoint>>>
  readonly businessMapMarkers?: Maybe<ReadonlyArray<Maybe<MapMarker>>>
  readonly currencyList: ReadonlyArray<Currency>
  readonly globals?: Maybe<Globals>
  readonly lnInvoicePaymentStatus: LnInvoicePaymentStatusPayload
  readonly me?: Maybe<User>
  readonly mobileVersions?: Maybe<ReadonlyArray<Maybe<MobileVersions>>>
  readonly onChainTxFee: OnChainTxFee
  readonly onChainUsdTxFee: OnChainUsdTxFee
  /** @deprecated TODO: remove. we don't need a non authenticated version of this query. the users can only do the query while authenticated */
  readonly quizQuestions?: Maybe<ReadonlyArray<Maybe<QuizQuestion>>>
  /** Returns 1 Sat and 1 Usd Cent price for the given currency */
  readonly realtimePrice: RealtimePrice
  /** @deprecated will be migrated to AccountDefaultWalletId */
  readonly userDefaultWalletId: Scalars["WalletId"]
  readonly usernameAvailable?: Maybe<Scalars["Boolean"]>
}

export type QueryAccountDefaultWalletArgs = {
  username: Scalars["Username"]
  walletCurrency?: InputMaybe<WalletCurrency>
}

export type QueryBtcPriceArgs = {
  currency?: Scalars["DisplayCurrency"]
}

export type QueryBtcPriceListArgs = {
  range: PriceGraphRange
}

export type QueryLnInvoicePaymentStatusArgs = {
  input: LnInvoicePaymentStatusInput
}

export type QueryOnChainTxFeeArgs = {
  address: Scalars["OnChainAddress"]
  amount: Scalars["SatAmount"]
  targetConfirmations?: InputMaybe<Scalars["TargetConfirmations"]>
  walletId: Scalars["WalletId"]
}

export type QueryOnChainUsdTxFeeArgs = {
  address: Scalars["OnChainAddress"]
  amount: Scalars["CentAmount"]
  targetConfirmations?: InputMaybe<Scalars["TargetConfirmations"]>
  walletId: Scalars["WalletId"]
}

export type QueryRealtimePriceArgs = {
  currency?: InputMaybe<Scalars["DisplayCurrency"]>
}

export type QueryUserDefaultWalletIdArgs = {
  username: Scalars["Username"]
}

export type QueryUsernameAvailableArgs = {
  username: Scalars["Username"]
}

export type Quiz = {
  readonly __typename: "Quiz"
  /** The reward in Satoshis for the quiz question */
  readonly amount: Scalars["SatAmount"]
  readonly completed: Scalars["Boolean"]
  readonly id: Scalars["ID"]
}

export type QuizCompletedInput = {
  readonly id: Scalars["ID"]
}

export type QuizCompletedPayload = {
  readonly __typename: "QuizCompletedPayload"
  readonly errors: ReadonlyArray<Error>
  readonly quiz?: Maybe<Quiz>
}

export type QuizQuestion = {
  readonly __typename: "QuizQuestion"
  /** The earn reward in Satoshis for the quiz question */
  readonly earnAmount: Scalars["SatAmount"]
  readonly id: Scalars["ID"]
}

export type RealtimePrice = {
  readonly __typename: "RealtimePrice"
  readonly btcSatPrice: PriceOfOneSatInMinorUnit
  readonly denominatorCurrency: Scalars["DisplayCurrency"]
  readonly id: Scalars["ID"]
  /** Unix timestamp (number of seconds elapsed since January 1, 1970 00:00:00 UTC) */
  readonly timestamp: Scalars["Timestamp"]
  readonly usdCentPrice: PriceOfOneUsdCentInMinorUnit
}

export type RealtimePriceInput = {
  readonly currency?: InputMaybe<Scalars["DisplayCurrency"]>
}

export type RealtimePricePayload = {
  readonly __typename: "RealtimePricePayload"
  readonly errors: ReadonlyArray<Error>
  readonly realtimePrice?: Maybe<RealtimePrice>
}

export type SatAmountPayload = {
  readonly __typename: "SatAmountPayload"
  readonly amount?: Maybe<Scalars["SatAmount"]>
  readonly errors: ReadonlyArray<Error>
}

export type SettlementVia =
  | SettlementViaIntraLedger
  | SettlementViaLn
  | SettlementViaOnChain

export type SettlementViaIntraLedger = {
  readonly __typename: "SettlementViaIntraLedger"
  /** Settlement destination: Could be null if the payee does not have a username */
  readonly counterPartyUsername?: Maybe<Scalars["Username"]>
  readonly counterPartyWalletId?: Maybe<Scalars["WalletId"]>
}

export type SettlementViaLn = {
  readonly __typename: "SettlementViaLn"
  /** @deprecated Shifting property to 'preImage' to improve granularity of the LnPaymentSecret type */
  readonly paymentSecret?: Maybe<Scalars["LnPaymentSecret"]>
  readonly preImage?: Maybe<Scalars["LnPaymentPreImage"]>
}

export type SettlementViaOnChain = {
  readonly __typename: "SettlementViaOnChain"
  readonly transactionHash: Scalars["OnChainTxHash"]
}

export type Subscription = {
  readonly __typename: "Subscription"
  readonly lnInvoicePaymentStatus: LnInvoicePaymentStatusPayload
  readonly myUpdates: MyUpdatesPayload
  readonly price: PricePayload
  /** Returns the price of 1 satoshi */
  readonly realtimePrice: RealtimePricePayload
}

export type SubscriptionLnInvoicePaymentStatusArgs = {
  input: LnInvoicePaymentStatusInput
}

export type SubscriptionPriceArgs = {
  input: PriceInput
}

export type SubscriptionRealtimePriceArgs = {
  input: RealtimePriceInput
}

export type SuccessPayload = {
  readonly __typename: "SuccessPayload"
  readonly errors: ReadonlyArray<Error>
  readonly success?: Maybe<Scalars["Boolean"]>
}

/**
 * Give details about an individual transaction.
 * Galoy have a smart routing system which is automatically
 * settling intraledger when both the payer and payee use the same wallet
 * therefore it's possible the transactions is being initiated onchain
 * or with lightning but settled intraledger.
 */
export type Transaction = {
  readonly __typename: "Transaction"
  readonly createdAt: Scalars["Timestamp"]
  readonly direction: TxDirection
  readonly id: Scalars["ID"]
  /** From which protocol the payment has been initiated. */
  readonly initiationVia: InitiationVia
  readonly memo?: Maybe<Scalars["Memo"]>
  /** Amount of the settlement currency sent or received. */
  readonly settlementAmount: Scalars["SignedAmount"]
  /** Wallet currency for transaction. */
  readonly settlementCurrency: WalletCurrency
  readonly settlementDisplayAmount: Scalars["SignedDisplayMajorAmount"]
  readonly settlementDisplayCurrency: Scalars["DisplayCurrency"]
  readonly settlementDisplayFee: Scalars["SignedDisplayMajorAmount"]
  readonly settlementFee: Scalars["SignedAmount"]
  /** Price in WALLETCURRENCY/SETTLEMENTUNIT at time of settlement. */
  readonly settlementPrice: PriceOfOneSettlementMinorUnitInDisplayMinorUnit
  /** To which protocol the payment has settled on. */
  readonly settlementVia: SettlementVia
  readonly status: TxStatus
}

/** A connection to a list of items. */
export type TransactionConnection = {
  readonly __typename: "TransactionConnection"
  /** A list of edges. */
  readonly edges?: Maybe<ReadonlyArray<TransactionEdge>>
  /** Information to aid in pagination. */
  readonly pageInfo: PageInfo
}

/** An edge in a connection. */
export type TransactionEdge = {
  readonly __typename: "TransactionEdge"
  /** A cursor for use in pagination */
  readonly cursor: Scalars["String"]
  /** The item at the end of the edge */
  readonly node: Transaction
}

export const TxDirection = {
  Receive: "RECEIVE",
  Send: "SEND",
} as const

export type TxDirection = typeof TxDirection[keyof typeof TxDirection]
export const TxNotificationType = {
  IntraLedgerPayment: "IntraLedgerPayment",
  IntraLedgerReceipt: "IntraLedgerReceipt",
  LnInvoicePaid: "LnInvoicePaid",
  OnchainPayment: "OnchainPayment",
  OnchainReceipt: "OnchainReceipt",
  OnchainReceiptPending: "OnchainReceiptPending",
} as const

export type TxNotificationType =
  typeof TxNotificationType[keyof typeof TxNotificationType]
export const TxStatus = {
  Failure: "FAILURE",
  Pending: "PENDING",
  Success: "SUCCESS",
} as const

export type TxStatus = typeof TxStatus[keyof typeof TxStatus]
/** A wallet belonging to an account which contains a USD balance and a list of transactions. */
export type UsdWallet = Wallet & {
  readonly __typename: "UsdWallet"
  readonly accountId: Scalars["ID"]
  readonly balance: Scalars["SignedAmount"]
  readonly id: Scalars["ID"]
  /** An unconfirmed incoming onchain balance. */
  readonly pendingIncomingBalance: Scalars["SignedAmount"]
  readonly transactions?: Maybe<TransactionConnection>
  readonly transactionsByAddress?: Maybe<TransactionConnection>
  readonly walletCurrency: WalletCurrency
}

/** A wallet belonging to an account which contains a USD balance and a list of transactions. */
export type UsdWalletTransactionsArgs = {
  after?: InputMaybe<Scalars["String"]>
  before?: InputMaybe<Scalars["String"]>
  first?: InputMaybe<Scalars["Int"]>
  last?: InputMaybe<Scalars["Int"]>
}

/** A wallet belonging to an account which contains a USD balance and a list of transactions. */
export type UsdWalletTransactionsByAddressArgs = {
  address: Scalars["OnChainAddress"]
  after?: InputMaybe<Scalars["String"]>
  before?: InputMaybe<Scalars["String"]>
  first?: InputMaybe<Scalars["Int"]>
  last?: InputMaybe<Scalars["Int"]>
}

export type User = {
  readonly __typename: "User"
  /**
   * Get single contact details.
   * Can include the transactions associated with the contact.
   * @deprecated will be moved to Accounts
   */
  readonly contactByUsername: UserContact
  /**
   * Get full list of contacts.
   * Can include the transactions associated with each contact.
   * @deprecated will be moved to account
   */
  readonly contacts: ReadonlyArray<UserContact>
  readonly createdAt: Scalars["Timestamp"]
  readonly defaultAccount: Account
  readonly id: Scalars["ID"]
  /**
   * Preferred language for user.
   * When value is 'default' the intent is to use preferred language from OS settings.
   */
  readonly language: Scalars["Language"]
  /** Phone number with international calling code. */
  readonly phone?: Maybe<Scalars["Phone"]>
  /**
   * List the quiz questions the user may have completed.
   * @deprecated use Quiz from Account instead
   */
  readonly quizQuestions: ReadonlyArray<UserQuizQuestion>
  /**
   * Optional immutable user friendly identifier.
   * @deprecated will be moved to @Handle in Account and Wallet
   */
  readonly username?: Maybe<Scalars["Username"]>
}

export type UserContactByUsernameArgs = {
  username: Scalars["Username"]
}

export type UserContact = {
  readonly __typename: "UserContact"
  /**
   * Alias the user can set for this contact.
   * Only the user can see the alias attached to their contact.
   */
  readonly alias?: Maybe<Scalars["ContactAlias"]>
  readonly id: Scalars["Username"]
  /** Paginated list of transactions sent to/from this contact. */
  readonly transactions?: Maybe<TransactionConnection>
  readonly transactionsCount: Scalars["Int"]
  /** Actual identifier of the contact. */
  readonly username: Scalars["Username"]
}

export type UserContactTransactionsArgs = {
  after?: InputMaybe<Scalars["String"]>
  before?: InputMaybe<Scalars["String"]>
  first?: InputMaybe<Scalars["Int"]>
  last?: InputMaybe<Scalars["Int"]>
}

export type UserContactUpdateAliasInput = {
  readonly alias: Scalars["ContactAlias"]
  readonly username: Scalars["Username"]
}

export type UserContactUpdateAliasPayload = {
  readonly __typename: "UserContactUpdateAliasPayload"
  readonly contact?: Maybe<UserContact>
  readonly errors: ReadonlyArray<Error>
}

export type UserLoginInput = {
  readonly code: Scalars["OneTimeAuthCode"]
  readonly phone: Scalars["Phone"]
}

export type UserLogoutInput = {
  readonly authToken: Scalars["AuthToken"]
}

export type UserQuizQuestion = {
  readonly __typename: "UserQuizQuestion"
  readonly completed: Scalars["Boolean"]
  readonly question: QuizQuestion
}

export type UserQuizQuestionUpdateCompletedInput = {
  readonly id: Scalars["ID"]
}

export type UserQuizQuestionUpdateCompletedPayload = {
  readonly __typename: "UserQuizQuestionUpdateCompletedPayload"
  readonly errors: ReadonlyArray<Error>
  readonly userQuizQuestion?: Maybe<UserQuizQuestion>
}

export type UserRequestAuthCodeInput = {
  readonly channel?: InputMaybe<PhoneCodeChannelType>
  readonly phone: Scalars["Phone"]
}

export type UserUpdate =
  | IntraLedgerUpdate
  | LnUpdate
  | OnChainUpdate
  | Price
  | RealtimePrice

export type UserUpdateLanguageInput = {
  readonly language: Scalars["Language"]
}

export type UserUpdateLanguagePayload = {
  readonly __typename: "UserUpdateLanguagePayload"
  readonly errors: ReadonlyArray<Error>
  readonly user?: Maybe<User>
}

export type UserUpdateUsernameInput = {
  readonly username: Scalars["Username"]
}

export type UserUpdateUsernamePayload = {
  readonly __typename: "UserUpdateUsernamePayload"
  readonly errors: ReadonlyArray<Error>
  readonly user?: Maybe<User>
}

/** A generic wallet which stores value in one of our supported currencies. */
export type Wallet = {
  readonly accountId: Scalars["ID"]
  readonly balance: Scalars["SignedAmount"]
  readonly id: Scalars["ID"]
  readonly pendingIncomingBalance: Scalars["SignedAmount"]
  /**
   * Transactions are ordered anti-chronologically,
   * ie: the newest transaction will be first
   */
  readonly transactions?: Maybe<TransactionConnection>
  /**
   * Transactions are ordered anti-chronologically,
   * ie: the newest transaction will be first
   */
  readonly transactionsByAddress?: Maybe<TransactionConnection>
  readonly walletCurrency: WalletCurrency
}

/** A generic wallet which stores value in one of our supported currencies. */
export type WalletTransactionsArgs = {
  after?: InputMaybe<Scalars["String"]>
  before?: InputMaybe<Scalars["String"]>
  first?: InputMaybe<Scalars["Int"]>
  last?: InputMaybe<Scalars["Int"]>
}

/** A generic wallet which stores value in one of our supported currencies. */
export type WalletTransactionsByAddressArgs = {
  address: Scalars["OnChainAddress"]
  after?: InputMaybe<Scalars["String"]>
  before?: InputMaybe<Scalars["String"]>
  first?: InputMaybe<Scalars["Int"]>
  last?: InputMaybe<Scalars["Int"]>
}

export const WalletCurrency = {
  Btc: "BTC",
  Usd: "USD",
} as const

export type WalletCurrency = typeof WalletCurrency[keyof typeof WalletCurrency]
export type CaptchaCreateChallengeMutationVariables = Exact<{ [key: string]: never }>

export type CaptchaCreateChallengeMutation = {
  readonly __typename: "Mutation"
  readonly captchaCreateChallenge: {
    readonly __typename: "CaptchaCreateChallengePayload"
    readonly errors: ReadonlyArray<{
      readonly __typename: "GraphQLApplicationError"
      readonly message: string
    }>
    readonly result?: {
      readonly __typename: "CaptchaCreateChallengeResult"
      readonly id: string
      readonly challengeCode: string
      readonly newCaptcha: boolean
      readonly failbackMode: boolean
    } | null
  }
}

export type CaptchaRequestAuthCodeMutationVariables = Exact<{
  input: CaptchaRequestAuthCodeInput
}>

export type CaptchaRequestAuthCodeMutation = {
  readonly __typename: "Mutation"
  readonly captchaRequestAuthCode: {
    readonly __typename: "SuccessPayload"
    readonly success?: boolean | null
    readonly errors: ReadonlyArray<{
      readonly __typename: "GraphQLApplicationError"
      readonly message: string
    }>
  }
}

export type BtcPriceListQueryVariables = Exact<{
  range: PriceGraphRange
}>

export type BtcPriceListQuery = {
  readonly __typename: "Query"
  readonly btcPriceList?: ReadonlyArray<{
    readonly __typename: "PricePoint"
    readonly timestamp: number
    readonly price: {
      readonly __typename: "Price"
      readonly base: number
      readonly offset: number
      readonly currencyUnit: string
    }
  } | null> | null
}

export type MainQueryVariables = Exact<{
  isAuthenticated: Scalars["Boolean"]
  recentTransactions?: InputMaybe<Scalars["Int"]>
}>

export type MainQuery = {
  readonly __typename: "Query"
  readonly globals?: {
    readonly __typename: "Globals"
    readonly nodesIds: ReadonlyArray<string>
    readonly lightningAddressDomain: string
  } | null
  readonly btcPrice?: {
    readonly __typename: "Price"
    readonly base: number
    readonly offset: number
    readonly currencyUnit: string
    readonly formattedAmount: string
  } | null
  readonly me?: {
    readonly __typename: "User"
    readonly id: string
    readonly language: string
    readonly username?: string | null
    readonly phone?: string | null
    readonly defaultAccount: {
      readonly __typename: "ConsumerAccount"
      readonly id: string
      readonly defaultWalletId: string
      readonly transactions?: {
        readonly __typename: "TransactionConnection"
        readonly pageInfo: {
          readonly __typename: "PageInfo"
          readonly hasNextPage: boolean
          readonly hasPreviousPage: boolean
          readonly startCursor?: string | null
          readonly endCursor?: string | null
        }
        readonly edges?: ReadonlyArray<{
          readonly __typename: "TransactionEdge"
          readonly cursor: string
          readonly node: {
            readonly __typename: "Transaction"
            readonly id: string
            readonly status: TxStatus
            readonly direction: TxDirection
            readonly memo?: string | null
            readonly createdAt: number
            readonly settlementAmount: number
            readonly settlementFee: number
            readonly settlementCurrency: WalletCurrency
            readonly settlementPrice: {
              readonly __typename: "PriceOfOneSettlementMinorUnitInDisplayMinorUnit"
              readonly base: number
              readonly offset: number
              readonly currencyUnit: string
              readonly formattedAmount: string
            }
            readonly initiationVia:
              | {
                  readonly __typename: "InitiationViaIntraLedger"
                  readonly counterPartyWalletId?: string | null
                  readonly counterPartyUsername?: string | null
                }
              | { readonly __typename: "InitiationViaLn"; readonly paymentHash: string }
              | { readonly __typename: "InitiationViaOnChain"; readonly address: string }
            readonly settlementVia:
              | {
                  readonly __typename: "SettlementViaIntraLedger"
                  readonly counterPartyWalletId?: string | null
                  readonly counterPartyUsername?: string | null
                }
              | {
                  readonly __typename: "SettlementViaLn"
                  readonly paymentSecret?: string | null
                }
              | {
                  readonly __typename: "SettlementViaOnChain"
                  readonly transactionHash: string
                }
          }
        }> | null
      } | null
      readonly wallets: ReadonlyArray<
        | {
            readonly __typename: "BTCWallet"
            readonly id: string
            readonly balance: number
            readonly walletCurrency: WalletCurrency
          }
        | {
            readonly __typename: "UsdWallet"
            readonly id: string
            readonly balance: number
            readonly walletCurrency: WalletCurrency
          }
      >
    }
  } | null
}

export type MeFragment = {
  readonly __typename: "User"
  readonly id: string
  readonly language: string
  readonly username?: string | null
  readonly phone?: string | null
  readonly defaultAccount: {
    readonly __typename: "ConsumerAccount"
    readonly id: string
    readonly defaultWalletId: string
    readonly transactions?: {
      readonly __typename: "TransactionConnection"
      readonly pageInfo: {
        readonly __typename: "PageInfo"
        readonly hasNextPage: boolean
        readonly hasPreviousPage: boolean
        readonly startCursor?: string | null
        readonly endCursor?: string | null
      }
      readonly edges?: ReadonlyArray<{
        readonly __typename: "TransactionEdge"
        readonly cursor: string
        readonly node: {
          readonly __typename: "Transaction"
          readonly id: string
          readonly status: TxStatus
          readonly direction: TxDirection
          readonly memo?: string | null
          readonly createdAt: number
          readonly settlementAmount: number
          readonly settlementFee: number
          readonly settlementCurrency: WalletCurrency
          readonly settlementPrice: {
            readonly __typename: "PriceOfOneSettlementMinorUnitInDisplayMinorUnit"
            readonly base: number
            readonly offset: number
            readonly currencyUnit: string
            readonly formattedAmount: string
          }
          readonly initiationVia:
            | {
                readonly __typename: "InitiationViaIntraLedger"
                readonly counterPartyWalletId?: string | null
                readonly counterPartyUsername?: string | null
              }
            | { readonly __typename: "InitiationViaLn"; readonly paymentHash: string }
            | { readonly __typename: "InitiationViaOnChain"; readonly address: string }
          readonly settlementVia:
            | {
                readonly __typename: "SettlementViaIntraLedger"
                readonly counterPartyWalletId?: string | null
                readonly counterPartyUsername?: string | null
              }
            | {
                readonly __typename: "SettlementViaLn"
                readonly paymentSecret?: string | null
              }
            | {
                readonly __typename: "SettlementViaOnChain"
                readonly transactionHash: string
              }
        }
      }> | null
    } | null
    readonly wallets: ReadonlyArray<
      | {
          readonly __typename: "BTCWallet"
          readonly id: string
          readonly balance: number
          readonly walletCurrency: WalletCurrency
        }
      | {
          readonly __typename: "UsdWallet"
          readonly id: string
          readonly balance: number
          readonly walletCurrency: WalletCurrency
        }
    >
  }
}

export type TransactionListFragment = {
  readonly __typename: "TransactionConnection"
  readonly pageInfo: {
    readonly __typename: "PageInfo"
    readonly hasNextPage: boolean
    readonly hasPreviousPage: boolean
    readonly startCursor?: string | null
    readonly endCursor?: string | null
  }
  readonly edges?: ReadonlyArray<{
    readonly __typename: "TransactionEdge"
    readonly cursor: string
    readonly node: {
      readonly __typename: "Transaction"
      readonly id: string
      readonly status: TxStatus
      readonly direction: TxDirection
      readonly memo?: string | null
      readonly createdAt: number
      readonly settlementAmount: number
      readonly settlementFee: number
      readonly settlementCurrency: WalletCurrency
      readonly settlementPrice: {
        readonly __typename: "PriceOfOneSettlementMinorUnitInDisplayMinorUnit"
        readonly base: number
        readonly offset: number
        readonly currencyUnit: string
        readonly formattedAmount: string
      }
      readonly initiationVia:
        | {
            readonly __typename: "InitiationViaIntraLedger"
            readonly counterPartyWalletId?: string | null
            readonly counterPartyUsername?: string | null
          }
        | { readonly __typename: "InitiationViaLn"; readonly paymentHash: string }
        | { readonly __typename: "InitiationViaOnChain"; readonly address: string }
      readonly settlementVia:
        | {
            readonly __typename: "SettlementViaIntraLedger"
            readonly counterPartyWalletId?: string | null
            readonly counterPartyUsername?: string | null
          }
        | {
            readonly __typename: "SettlementViaLn"
            readonly paymentSecret?: string | null
          }
        | {
            readonly __typename: "SettlementViaOnChain"
            readonly transactionHash: string
          }
    }
  }> | null
}

export const TransactionListFragmentDoc = gql`
  fragment TransactionList on TransactionConnection {
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
      __typename
    }
    edges {
      cursor
      node {
        __typename
        id
        status
        direction
        memo
        createdAt
        settlementAmount
        settlementFee
        settlementCurrency
        settlementPrice {
          base
          offset
          currencyUnit
          formattedAmount
          __typename
        }
        initiationVia {
          __typename
          ... on InitiationViaIntraLedger {
            counterPartyWalletId
            counterPartyUsername
            __typename
          }
          ... on InitiationViaLn {
            paymentHash
            __typename
          }
          ... on InitiationViaOnChain {
            address
            __typename
          }
        }
        settlementVia {
          __typename
          ... on SettlementViaIntraLedger {
            counterPartyWalletId
            counterPartyUsername
            __typename
          }
          ... on SettlementViaLn {
            paymentSecret
            __typename
          }
          ... on SettlementViaOnChain {
            transactionHash
            __typename
          }
        }
      }
      __typename
    }
    __typename
  }
`
export const MeFragmentDoc = gql`
  fragment Me on User {
    id
    language
    username
    phone
    defaultAccount {
      id
      defaultWalletId
      transactions(first: $recentTransactions) {
        ...TransactionList
        __typename
      }
      wallets {
        id
        balance
        walletCurrency
        __typename
      }
      __typename
    }
    __typename
  }
  ${TransactionListFragmentDoc}
`
export const CaptchaCreateChallengeDocument = gql`
  mutation captchaCreateChallenge {
    captchaCreateChallenge {
      errors {
        __typename
        message
      }
      result {
        __typename
        id
        challengeCode
        newCaptcha
        failbackMode
      }
      __typename
    }
  }
`
export type CaptchaCreateChallengeMutationFn = Apollo.MutationFunction<
  CaptchaCreateChallengeMutation,
  CaptchaCreateChallengeMutationVariables
>

/**
 * __useCaptchaCreateChallengeMutation__
 *
 * To run a mutation, you first call `useCaptchaCreateChallengeMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCaptchaCreateChallengeMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [captchaCreateChallengeMutation, { data, loading, error }] = useCaptchaCreateChallengeMutation({
 *   variables: {
 *   },
 * });
 */
export function useCaptchaCreateChallengeMutation(
  baseOptions?: Apollo.MutationHookOptions<
    CaptchaCreateChallengeMutation,
    CaptchaCreateChallengeMutationVariables
  >,
) {
  const options = { ...defaultOptions, ...baseOptions }
  return Apollo.useMutation<
    CaptchaCreateChallengeMutation,
    CaptchaCreateChallengeMutationVariables
  >(CaptchaCreateChallengeDocument, options)
}
export type CaptchaCreateChallengeMutationHookResult = ReturnType<
  typeof useCaptchaCreateChallengeMutation
>
export type CaptchaCreateChallengeMutationResult =
  Apollo.MutationResult<CaptchaCreateChallengeMutation>
export type CaptchaCreateChallengeMutationOptions = Apollo.BaseMutationOptions<
  CaptchaCreateChallengeMutation,
  CaptchaCreateChallengeMutationVariables
>
export const CaptchaRequestAuthCodeDocument = gql`
  mutation captchaRequestAuthCode($input: CaptchaRequestAuthCodeInput!) {
    captchaRequestAuthCode(input: $input) {
      errors {
        __typename
        message
      }
      success
      __typename
    }
  }
`
export type CaptchaRequestAuthCodeMutationFn = Apollo.MutationFunction<
  CaptchaRequestAuthCodeMutation,
  CaptchaRequestAuthCodeMutationVariables
>

/**
 * __useCaptchaRequestAuthCodeMutation__
 *
 * To run a mutation, you first call `useCaptchaRequestAuthCodeMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCaptchaRequestAuthCodeMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [captchaRequestAuthCodeMutation, { data, loading, error }] = useCaptchaRequestAuthCodeMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useCaptchaRequestAuthCodeMutation(
  baseOptions?: Apollo.MutationHookOptions<
    CaptchaRequestAuthCodeMutation,
    CaptchaRequestAuthCodeMutationVariables
  >,
) {
  const options = { ...defaultOptions, ...baseOptions }
  return Apollo.useMutation<
    CaptchaRequestAuthCodeMutation,
    CaptchaRequestAuthCodeMutationVariables
  >(CaptchaRequestAuthCodeDocument, options)
}
export type CaptchaRequestAuthCodeMutationHookResult = ReturnType<
  typeof useCaptchaRequestAuthCodeMutation
>
export type CaptchaRequestAuthCodeMutationResult =
  Apollo.MutationResult<CaptchaRequestAuthCodeMutation>
export type CaptchaRequestAuthCodeMutationOptions = Apollo.BaseMutationOptions<
  CaptchaRequestAuthCodeMutation,
  CaptchaRequestAuthCodeMutationVariables
>
export const BtcPriceListDocument = gql`
  query btcPriceList($range: PriceGraphRange!) {
    btcPriceList(range: $range) {
      timestamp
      price {
        base
        offset
        currencyUnit
      }
    }
  }
`

/**
 * __useBtcPriceListQuery__
 *
 * To run a query within a React component, call `useBtcPriceListQuery` and pass it any options that fit your needs.
 * When your component renders, `useBtcPriceListQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useBtcPriceListQuery({
 *   variables: {
 *      range: // value for 'range'
 *   },
 * });
 */
export function useBtcPriceListQuery(
  baseOptions: Apollo.QueryHookOptions<BtcPriceListQuery, BtcPriceListQueryVariables>,
) {
  const options = { ...defaultOptions, ...baseOptions }
  return Apollo.useQuery<BtcPriceListQuery, BtcPriceListQueryVariables>(
    BtcPriceListDocument,
    options,
  )
}
export function useBtcPriceListLazyQuery(
  baseOptions?: Apollo.LazyQueryHookOptions<
    BtcPriceListQuery,
    BtcPriceListQueryVariables
  >,
) {
  const options = { ...defaultOptions, ...baseOptions }
  return Apollo.useLazyQuery<BtcPriceListQuery, BtcPriceListQueryVariables>(
    BtcPriceListDocument,
    options,
  )
}
export type BtcPriceListQueryHookResult = ReturnType<typeof useBtcPriceListQuery>
export type BtcPriceListLazyQueryHookResult = ReturnType<typeof useBtcPriceListLazyQuery>
export type BtcPriceListQueryResult = Apollo.QueryResult<
  BtcPriceListQuery,
  BtcPriceListQueryVariables
>
export const MainDocument = gql`
  query main($isAuthenticated: Boolean!, $recentTransactions: Int) {
    globals {
      nodesIds
      lightningAddressDomain
      __typename
    }
    btcPrice {
      base
      offset
      currencyUnit
      formattedAmount
      __typename
    }
    me @include(if: $isAuthenticated) {
      ...Me
      __typename
    }
  }
  ${MeFragmentDoc}
`

/**
 * __useMainQuery__
 *
 * To run a query within a React component, call `useMainQuery` and pass it any options that fit your needs.
 * When your component renders, `useMainQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useMainQuery({
 *   variables: {
 *      isAuthenticated: // value for 'isAuthenticated'
 *      recentTransactions: // value for 'recentTransactions'
 *   },
 * });
 */
export function useMainQuery(
  baseOptions: Apollo.QueryHookOptions<MainQuery, MainQueryVariables>,
) {
  const options = { ...defaultOptions, ...baseOptions }
  return Apollo.useQuery<MainQuery, MainQueryVariables>(MainDocument, options)
}
export function useMainLazyQuery(
  baseOptions?: Apollo.LazyQueryHookOptions<MainQuery, MainQueryVariables>,
) {
  const options = { ...defaultOptions, ...baseOptions }
  return Apollo.useLazyQuery<MainQuery, MainQueryVariables>(MainDocument, options)
}
export type MainQueryHookResult = ReturnType<typeof useMainQuery>
export type MainLazyQueryHookResult = ReturnType<typeof useMainLazyQuery>
export type MainQueryResult = Apollo.QueryResult<MainQuery, MainQueryVariables>
